### ISSUE TITLE
Pretty big spelling mistake

### ISSUE THREAD

**Issue by dezzie** [watson-developer-cloud/professor-languo#7]
Since it's the only instruction the user receives. Should be "relevant."

You can ask the app the difference between "relevant" and "relevent" ;)

https://github.com/watson-developer-cloud/professor-languo/blob/master/professor-languo/src/main/webapp/index.html#L26
https://github.com/watson-developer-cloud/professor-languo/blob/master/professor-languo/src/main/webapp/index.html#L32

**Comment by stevenoh93** [comment]
Thank you for pointing out the spelling mistake! We're fixing it now.

**Comment by germanattanasio** [comment]
fixed by @stevenoh93
